# Generated by Django 2.2.7 on 2019-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(null=True, verbose_name='level'),
        ),
    ]
