# Generated by Django 2.2.7 on 2019-12-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20191210_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(max_length=200, null=True, verbose_name='link'),
        ),
    ]
